# Generated by Django 4.1.6 on 2023-05-29 17:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, editable=False, max_length=5, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("email", models.EmailField(max_length=500, unique=True)),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number must be entered in the format: '+8801XXXXXXXXX'.",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^(?:\\+88|88)?(01[3-9]\\d{8})$"
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "due",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
