# Generated by Django 4.1.6 on 2023-06-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerapp", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="mobile_number",
        ),
        migrations.AddField(
            model_name="customer",
            name="totalSpent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
