# Generated by Django 4.1.6 on 2023-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerapp", "0004_remove_customer_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AddField(
            model_name="customer",
            name="pay",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
