# Generated by Django 4.1.6 on 2023-06-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customerapp", "0005_remove_customer_email_remove_customer_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="pay",
        ),
    ]
