# Generated by Django 4.1.6 on 2023-08-24 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_delete_customer"),
        ("productapp", "0003_alter_product_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, editable=False, max_length=5, null=True
                    ),
                ),
                (
                    "totalSpent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "due",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ROrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, editable=False, max_length=5, null=True
                    ),
                ),
                (
                    "subPrice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "totalPrice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "duePrice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "vat",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "vatParcent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "discountParcent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "transport",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("returnTime", models.IntegerField(default=0)),
                (
                    "retailerID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.retailer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RetailerPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, editable=False, max_length=20, null=True
                    ),
                ),
                (
                    "customerID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.retailer",
                    ),
                ),
                (
                    "orderID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.rorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RetailerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                (
                    "orderID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.rorder",
                    ),
                ),
                (
                    "retailerID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.retailer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sellPrice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("unit", models.IntegerField(default=0.0)),
                (
                    "orderID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.rorder",
                    ),
                ),
                (
                    "productID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_product_orders",
                        to="productapp.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
