# Generated by Django 4.1.6 on 2024-02-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0003_alter_product_stock"),
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductOrder",
            new_name="ProductROrder",
        ),
    ]
