# Generated by Django 4.1.6 on 2023-05-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
