# Generated by Django 4.1.6 on 2023-05-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile_pic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
