# Generated by Django 4.1.6 on 2023-05-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="user",
        ),
    ]
