# Generated by Django 4.1.6 on 2023-05-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unique_id",
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
