# Generated by Django 4.1.6 on 2023-06-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0002_remove_product_user_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0.0),
        ),
    ]
