# Generated by Django 4.1.6 on 2024-04-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0003_alter_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
