# Generated by Django 4.1.6 on 2023-06-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sellapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customerOrderID",
        ),
        migrations.RemoveField(
            model_name="order",
            name="productOrderID",
        ),
        migrations.AddField(
            model_name="customerorder",
            name="orderID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sellapp.order",
            ),
        ),
        migrations.AddField(
            model_name="productorder",
            name="orderID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sellapp.order",
            ),
        ),
    ]
