# Generated by Django 4.1.6 on 2023-06-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellapp", "0002_remove_order_customerorderid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="order",
            name="transport",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="order",
            name="vat",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
