# Generated by Django 4.1.6 on 2023-06-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customerapp", "0006_remove_customer_pay"),
        ("sellapp", "0003_order_discount_order_transport_order_vat"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customerID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customerapp.customer",
            ),
        ),
    ]
