# Generated by Django 4.1.6 on 2023-06-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellapp", "0004_order_customerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="returnTime",
            field=models.IntegerField(default=0),
        ),
    ]
