# Generated by Django 4.1.6 on 2023-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellapp", "0005_order_returntime"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discountParcent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="order",
            name="vatParcent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
